clientId: ""
guildId: ""

commands:
  - name: "ping" # /ping
    description: "Pong!"
    subcommand:
      - name: "pong" #/ping pong
        description: "Pong!"
    subcommand_groups:
      - name: "foo"
        description: "Foo!"
        subcommands:
          - name: "bar" # /ping foo bar
            description: "Bar!"